name: Terraform and Ansible

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_vm_admin_password: ${{ secrets.TF_VAR_VM_ADMIN_PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup do Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format
        run: terraform fmt -check -diff

      - name: Executar o linter
        uses: terraform-linters/setup-tflint@v4

      # Específico para IaC
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          soft_fail: true

      # tsec específico para Terraform
      - name: Run tsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

      - name: Inicializar Terraform
        run: terraform init

      - name: Criar o Terraform plan
        run: terraform plan

      - name: Executar o Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve